/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as CasesRouteRouteImport } from './routes/cases/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as CasesProductWalltimeRouteImport } from './routes/cases/product/walltime'
import { Route as CasesProductRicsRouteImport } from './routes/cases/product/rics'
import { Route as CasesProductAthayogaRouteImport } from './routes/cases/product/athayoga'
import { Route as CasesGameExample2RouteImport } from './routes/cases/game/example2'
import { Route as CasesGameExampleRouteImport } from './routes/cases/game/example'

const CasesRouteRoute = CasesRouteRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesProductWalltimeRoute = CasesProductWalltimeRouteImport.update({
  id: '/product/walltime',
  path: '/product/walltime',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesProductRicsRoute = CasesProductRicsRouteImport.update({
  id: '/product/rics',
  path: '/product/rics',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesProductAthayogaRoute = CasesProductAthayogaRouteImport.update({
  id: '/product/athayoga',
  path: '/product/athayoga',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesGameExample2Route = CasesGameExample2RouteImport.update({
  id: '/game/example2',
  path: '/game/example2',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesGameExampleRoute = CasesGameExampleRouteImport.update({
  id: '/game/example',
  path: '/game/example',
  getParentRoute: () => CasesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteRouteWithChildren
  '/cases/': typeof CasesIndexRoute
  '/cases/game/example': typeof CasesGameExampleRoute
  '/cases/game/example2': typeof CasesGameExample2Route
  '/cases/product/athayoga': typeof CasesProductAthayogaRoute
  '/cases/product/rics': typeof CasesProductRicsRoute
  '/cases/product/walltime': typeof CasesProductWalltimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesIndexRoute
  '/cases/game/example': typeof CasesGameExampleRoute
  '/cases/game/example2': typeof CasesGameExample2Route
  '/cases/product/athayoga': typeof CasesProductAthayogaRoute
  '/cases/product/rics': typeof CasesProductRicsRoute
  '/cases/product/walltime': typeof CasesProductWalltimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteRouteWithChildren
  '/cases/': typeof CasesIndexRoute
  '/cases/game/example': typeof CasesGameExampleRoute
  '/cases/game/example2': typeof CasesGameExample2Route
  '/cases/product/athayoga': typeof CasesProductAthayogaRoute
  '/cases/product/rics': typeof CasesProductRicsRoute
  '/cases/product/walltime': typeof CasesProductWalltimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/cases/'
    | '/cases/game/example'
    | '/cases/game/example2'
    | '/cases/product/athayoga'
    | '/cases/product/rics'
    | '/cases/product/walltime'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/cases/game/example'
    | '/cases/game/example2'
    | '/cases/product/athayoga'
    | '/cases/product/rics'
    | '/cases/product/walltime'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/cases/'
    | '/cases/game/example'
    | '/cases/game/example2'
    | '/cases/product/athayoga'
    | '/cases/product/rics'
    | '/cases/product/walltime'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRouteRoute: typeof CasesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/product/walltime': {
      id: '/cases/product/walltime'
      path: '/product/walltime'
      fullPath: '/cases/product/walltime'
      preLoaderRoute: typeof CasesProductWalltimeRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/product/rics': {
      id: '/cases/product/rics'
      path: '/product/rics'
      fullPath: '/cases/product/rics'
      preLoaderRoute: typeof CasesProductRicsRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/product/athayoga': {
      id: '/cases/product/athayoga'
      path: '/product/athayoga'
      fullPath: '/cases/product/athayoga'
      preLoaderRoute: typeof CasesProductAthayogaRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/game/example2': {
      id: '/cases/game/example2'
      path: '/game/example2'
      fullPath: '/cases/game/example2'
      preLoaderRoute: typeof CasesGameExample2RouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/game/example': {
      id: '/cases/game/example'
      path: '/game/example'
      fullPath: '/cases/game/example'
      preLoaderRoute: typeof CasesGameExampleRouteImport
      parentRoute: typeof CasesRouteRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/cases/route' {
  const createFileRoute: CreateFileRoute<
    '/cases',
    FileRoutesByPath['/cases']['parentRoute'],
    FileRoutesByPath['/cases']['id'],
    FileRoutesByPath['/cases']['path'],
    FileRoutesByPath['/cases']['fullPath']
  >
}
declare module './routes/cases/index' {
  const createFileRoute: CreateFileRoute<
    '/cases/',
    FileRoutesByPath['/cases/']['parentRoute'],
    FileRoutesByPath['/cases/']['id'],
    FileRoutesByPath['/cases/']['path'],
    FileRoutesByPath['/cases/']['fullPath']
  >
}
declare module './routes/cases/game/example' {
  const createFileRoute: CreateFileRoute<
    '/cases/game/example',
    FileRoutesByPath['/cases/game/example']['parentRoute'],
    FileRoutesByPath['/cases/game/example']['id'],
    FileRoutesByPath['/cases/game/example']['path'],
    FileRoutesByPath['/cases/game/example']['fullPath']
  >
}
declare module './routes/cases/game/example2' {
  const createFileRoute: CreateFileRoute<
    '/cases/game/example2',
    FileRoutesByPath['/cases/game/example2']['parentRoute'],
    FileRoutesByPath['/cases/game/example2']['id'],
    FileRoutesByPath['/cases/game/example2']['path'],
    FileRoutesByPath['/cases/game/example2']['fullPath']
  >
}
declare module './routes/cases/product/athayoga' {
  const createFileRoute: CreateFileRoute<
    '/cases/product/athayoga',
    FileRoutesByPath['/cases/product/athayoga']['parentRoute'],
    FileRoutesByPath['/cases/product/athayoga']['id'],
    FileRoutesByPath['/cases/product/athayoga']['path'],
    FileRoutesByPath['/cases/product/athayoga']['fullPath']
  >
}
declare module './routes/cases/product/rics' {
  const createFileRoute: CreateFileRoute<
    '/cases/product/rics',
    FileRoutesByPath['/cases/product/rics']['parentRoute'],
    FileRoutesByPath['/cases/product/rics']['id'],
    FileRoutesByPath['/cases/product/rics']['path'],
    FileRoutesByPath['/cases/product/rics']['fullPath']
  >
}
declare module './routes/cases/product/walltime' {
  const createFileRoute: CreateFileRoute<
    '/cases/product/walltime',
    FileRoutesByPath['/cases/product/walltime']['parentRoute'],
    FileRoutesByPath['/cases/product/walltime']['id'],
    FileRoutesByPath['/cases/product/walltime']['path'],
    FileRoutesByPath['/cases/product/walltime']['fullPath']
  >
}

interface CasesRouteRouteChildren {
  CasesIndexRoute: typeof CasesIndexRoute
  CasesGameExampleRoute: typeof CasesGameExampleRoute
  CasesGameExample2Route: typeof CasesGameExample2Route
  CasesProductAthayogaRoute: typeof CasesProductAthayogaRoute
  CasesProductRicsRoute: typeof CasesProductRicsRoute
  CasesProductWalltimeRoute: typeof CasesProductWalltimeRoute
}

const CasesRouteRouteChildren: CasesRouteRouteChildren = {
  CasesIndexRoute: CasesIndexRoute,
  CasesGameExampleRoute: CasesGameExampleRoute,
  CasesGameExample2Route: CasesGameExample2Route,
  CasesProductAthayogaRoute: CasesProductAthayogaRoute,
  CasesProductRicsRoute: CasesProductRicsRoute,
  CasesProductWalltimeRoute: CasesProductWalltimeRoute,
}

const CasesRouteRouteWithChildren = CasesRouteRoute._addFileChildren(
  CasesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRouteRoute: CasesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
